# hardstatus line theme
#set-option -g status-fg white
set-option -g status-style bg=default
set-option -g status-justify left
set-option -g status-left-length 50
set-option -g status-interval 2
set-option -g status-left '[ #[fg=white,bright]#h ] #[default]'
set-option -g status-right-length 80
set-option -g status-right '[ #($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load -a 1 --interval 2) | #[fg=white,bright]%m/%d %H:%M #[fg=default]]'
set-window-option -g window-status-current-format '#[fg=red,bg=default]( #[fg=white,bright,bg=default]#I:#W#[fg=red,nobright,bg=default] )#[fg=default]'
set -g base-index 1
set -g pane-base-index 1

# List of plugins
set -g @tpm_plugins '           \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tmux-resurrect  \
   thewtex/tmux-mem-cpu-load    \
'

run '~/.tmux/plugins/tpm/tpm'
